### ISSUE TITLE
Modify the code for proteins

### ISSUE THREAD

**Issue by smruti241** [GaganMalik025/Classification_of_Interacting_Non-Interacting_RNA#1]
Hii,

I want to modify this code for proteins. How to do it, please help me. Thanks!

**Comment by GaganMalik025** [comment]
How exactly do you want to modify it?

**Comment by smruti241** [comment]
I want to modify it for proteins. I tried it but failed due to data reshape

**Comment by smruti241** [comment]
If you can tell me I can share the data with you

**Comment by GaganMalik025** [comment]
First, compare your data with my data. Is it in the same format?

**Comment by smruti241** [comment]
Yes train.csv contain label (output +1 for positive and -1 for negative sequence) and Sequence (amino acid sequence) of a protein (input)
test.csv contain Sequence (amino acid sequence) of a protein (input) and ID of sequence
sample.csv should contain ID of sequence and label (output) either -1 or 1

**Comment by smruti241** [comment]
I hope you get it

**Comment by GaganMalik025** [comment]
Send me your Data

**Comment by smruti241** [comment]
[train.csv.zip](https://github.com/GaganMalik025/Classification_of_Interacting_Non-Interacting_RNA/files/9894388/train.csv.zip)
[test.csv](https://github.com/GaganMalik025/Classification_of_Interacting_Non-Interacting_RNA/files/9894389/test.csv)
[sample.csv](https://github.com/GaganMalik025/Classification_of_Interacting_Non-Interacting_RNA/files/9894390/sample.csv)

**Comment by smruti241** [comment]
Please don't share this with anyone. After downloading, delete it from here or otherwise I will delete it after half an hour

**Comment by GaganMalik025** [comment]
So basically I think your columns are reversed right? Label is the first column while sequence is the 2nd

**Comment by smruti241** [comment]
Yes

**Comment by GaganMalik025** [comment]
Compared to my data's columns, where Label is the 2nd column while Sequence is the first column

**Comment by smruti241** [comment]
Yes

**Comment by smruti241** [comment]
Can I delete the data comment?

**Comment by GaganMalik025** [comment]
So just edit your data and make the format the same as my data

**Comment by smruti241** [comment]
Ok and in reshape the data the numbers would be same ?

**Comment by GaganMalik025** [comment]
Just edit your data in both train.csv and test.csv where first column will be your sequence and 2nd column will be your label. I don't think any other changes would be required

**Comment by smruti241** [comment]
And where should I use sample.csv? In your code, only train.csv and test.csv are there

**Comment by GaganMalik025** [comment]
Usage of "sample" data is not mandatory. For example in my code I haven't used a sample data

**Comment by smruti241** [comment]
Then why it is given? I think it is for validation

**Comment by smruti241** [comment]
I need more accuracy score. Like if I want my model to give 90% accuracy how to modify it then?

**Comment by GaganMalik025** [comment]
How should I know why a sample data is given to you?

**Comment by smruti241** [comment]
Ok thank you so much for your help

**Comment by GaganMalik025** [comment]
I don't think my code can provide accuracy that high but it can depending upon the data being used for testing.

**Comment by GaganMalik025** [comment]
Rest just see my data and compare it to yours and make edits where required if you face any more errors. It's pretty simple you can do it.

**Comment by smruti241** [comment]
my train.csv has sequence and label and test.csv has sequence and ID.
Yours has sequence and label in both the csv files. Thats why I am getting error

**Comment by smruti241** [comment]
can you please tell me where should I modify? The error is 
Traceback (most recent call last):
  File "classify_proteins.py", line 50, in <module>
    data.reshape(shape)
  File "/home/smrutip/anaconda3/envs/dnabert/lib/python3.6/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'reshape'

**Comment by smruti241** [comment]
Traceback (most recent call last):
  File "proteins.py", line 58, in <module>
    processed_data = np.reshape(processed_data, (330862, 357))        #binary conversion done
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/smrutip/anaconda3/envs/dnabert/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/smrutip/anaconda3/envs/dnabert/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 6560 into shape (330862,357
